import {
  BookOpen,
  Users,
  Rocket,
  Lightbulb,
  Heart,
  Globe,
  Home,
  FileText,
  Settings,
  Star,
  Calendar,
  Mail,
  Bell,
  Clipboard,
  Award,
  Tag,
  ShoppingCart,
  DollarSign,
  Handshake,
} from "lucide-react";

export const availableIcons = [
  { name: "BookOpen", icon: <BookOpen className="w-5 h-5" /> },
  { name: "Users", icon: <Users className="w-5 h-5" /> },
  { name: "Rocket", icon: <Rocket className="w-5 h-5" /> },
  { name: "Lightbulb", icon: <Lightbulb className="w-5 h-5" /> },
  { name: "Heart", icon: <Heart className="w-5 h-5" /> },
  { name: "Globe", icon: <Globe className="w-5 h-5" /> },
  { name: "Home", icon: <Home className="w-5 h-5" /> },
  { name: "FileText", icon: <FileText className="w-5 h-5" /> },
  { name: "Settings", icon: <Settings className="w-5 h-5" /> },
  { name: "Star", icon: <Star className="w-5 h-5" /> },
  { name: "Calendar", icon: <Calendar className="w-5 h-5" /> },
  { name: "Mail", icon: <Mail className="w-5 h-5" /> },
  { name: "Bell", icon: <Bell className="w-5 h-5" /> },
  { name: "Clipboard", icon: <Clipboard className="w-5 h-5" /> },
  { name: "Award", icon: <Award className="w-5 h-5" /> },
  { name: "Tag", icon: <Tag className="w-5 h-5" /> },
  { name: "ShoppingCart", icon: <ShoppingCart className="w-5 h-5" /> },
  { name: "DollarSign", icon: <DollarSign className="w-5 h-5" /> },
  { name: "Handshake", icon: <Handshake className="w-5 h-5" /> },
];
